### ISSUE TITLE
Evrything is throwing an exception!

### ISSUE THREAD

**Issue by almafa64** [PixelVision8/PixelVision8#434]
**I downloaded the verison 0.9.0 on windows.**
I started the program and then when i want to run, build, make new project, or anything else is throwing this message: _**"Exception has been thrown by the target of an invocation."**_ when i make a new project then the Ctrl+4 is working but if i want to play the game it's don't do anything just the esc button working.

And the console is showing this message: 
**"! Exception has been thrown by the target of an invocation.
Press Ctrl + 4 to reload the current game.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args)
   at MoonSharp.Interpreter.Interop.FunctionMemberDescriptorBase.<>c__DisplayClass29_0.<GetCallback>b__0(ScriptExecutionContext c, CallbackArguments a)
   at MoonSharp.Interpreter.Execution.VM.Processor.Internal_ExecCall(Int32 argsCount, Int32 instructionPtr, CallbackFunction handler, CallbackFunction continuation, Boolean thisCall, String debugText, DynValue unwindHandler)
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr)
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args)
   at PixelVision8.Engine.Chips.LuaGameChip.Update(Int32 timeDelta)
   at PixelVision8.Engine.PixelVisionEngine.Update(Int32 timeDelta)
   at PixelVision8.Runner.GameRunner.Update(GameTime gameTime)
   at PixelVision8.Runner.PixelVision8Runner.Update(GameTime gameTime)"**

Thank you in advance for your help!

**Comment by almafa64** [comment]
Ok i find the error. It was an older version. I donwloaded the new version from the pixel version 8 webpage and it's working.
